pipeline {
    agent {
        docker {
            image 'python-docker-agent'
            args '-u root -v /var/run/docker.sock:/var/run/docker.sock'
        }
    }

    environment {
        WORKDIR = "task_1"  
        IMAGE_NAME = "ci-demo-app:${env.BUILD_NUMBER}"
    }

    stages {

        stage("Checkout") {
            steps {
                checkout scm
                sh "ls -R ."
            }
        }

        stage("Install & Test") {
            steps {
                sh "cd ${WORKDIR} && python -m pip install --upgrade pip"
                sh "cd ${WORKDIR} && pip install -r requirements.txt"
                sh "cd ${WORKDIR} && PYTHONPATH=. pytest -q"
            }
        }

        stage("Build Docker Image") {
            steps {
                sh "cd ${WORKDIR} && docker build -t ${IMAGE_NAME} ."
            }
        }

        stage("Run Container") {
            steps {
                sh '''
                    docker rm -f ci-demo-running || true
                    docker run -d --name ci-demo-running -p 5001:5000 ${IMAGE_NAME}
                '''
            }
        }
    }

    post {
        success {
            echo "Build SUCCESS: ${IMAGE_NAME}"
        }
        failure {
            echo "Build FAILED"
        }
    }
}
